SEASON_EPISODE_MAP = {
    1: range(1, 25),
    2: range(25, 48),
    3: range(48, 74),
}

HONORIFIC_REPLACEMENTS = {
    '-san': '{**-san}',
    '-kun': '{**-kun}',
    '-chan': '{**-chan}',
    '-senpai': '{**-senpai}',
    '-sama': '{*}{*-sama}',
    '-dono': '{*}{*-dono}',
    '-sensei': '{*}{*-sensei}',
}

CHARACTER_NAMES = [
    'Yuji Itadori',
    'Yuta Okkotsu',
    'Megumi Fushiguro',
    'Maki Zenin',
    'Nobara Kugisaki',
    'Toge Inumaki',
    'Mai Zenin',
    'Aoi Todo',
    'Noritoshi Kamo',
    'Mono Nishimiya',
    'Kasumi Miwa',
    'Kokichi Muta',
    'Arata Nitta',
    'Akari Nitta',
    'Satoru Gojo',
    'Suguru Geto',
    'Kento Nanami',
    'Yu Haibara',
    'Iori Utahime',
    'Shoko Ieiri',
    'Kiyotaka Ijichi',
    'Masamichi Yaga',
    'Toji Fushiguro',
    'Riko Amanai',
    'Misato Kuroi',
    'Yuki Tsukumo',
    'Kinji Hakari',
    'Kirara Hoshi',
    'Takuma Ino',
    'Naobito Zenin',
    'Naoya Zenin',
    'Ogi Zenin',
    'Ranta Zenin',
    'Jinchi Zenin',
    'Chojuro Zenin',
    'Nobuaki Zenin',
    'Hajime Kashimo',
    'Ryu Ishigori',
    'Takako Uro',
    'Hana Kurusu',
    'Hiromi Higuruma',
    'Fumihiko Takaba',
    'Chizuru Hari',
    'Iori Hazenoki',
    'Rin Amai',
    'Hagane Daido',
    'Rokujushi Miyo',
]

TERMINOLOGY_REPLACEMENTS = {
    'Jujutsu High': 'Jujutsu Tech',
    'Zen\'in': 'Zenin',
    'veil': 'Veil',
    'pact': 'Pact',
    'Pact': 'Binding Vow',
    'Heavenly Pact': 'Heavenly Restriction',
    'Sensei': '{*}Teach{*Sensei}',
    'Gojo{*}{*-sensei}': '{*}Mr. Gojo{*Gojo-sensei}',
    'Geto{*}{*-sama}': '{*}Master Geto{*Geto-sama}',
    'Tengen{*}{*-sama}': '{*}Master Tengen{*Tengen-sama}',
    'Sukuna{*}{*-sama}': '{*}Lord Sukuna{*Sukuna-sama}',
    'Nanami{**-san}': '{*}Mr. Nanami{*Nanami-san}',
    'Ijichi{**-san}': '{*}Mr. Ijichi{*Ijichi-san}',
    'Ieiri{**-san}': '{*}Miss Ieiri{*Ieiri-san}',
    'Riko{*}{*-sama}': '{*}Lady Riko{*Riko-sama}',
    'Mei{**-san}': '{*}Miss Mei{*Mei-san}',
    'Nee{*}{*-sama}': '{*}Sister{*Nee-sama}',
    'Onii{**-chan}': '{*}Big Brother{*Onii-chan}',
    'Nii{**-chan}': '{*}Big Bro{*Nii-chan}',
}
